### ISSUE TITLE
nuxi add api does not add to server directory

### ISSUE THREAD

**Issue by bigredwill** [nuxt-hub/starter#13]
```
$ npx nuxi add api magazines --get                              
ℹ Creating directory /Users/home/20-Projects/skateboard.fyi/app/server/api                                                                                           
ℹ 🪄 Generated a new api in /Users/home/20-Projects/skateboard.fyi/app/server/api/magazines.get.ts 
````
But, this starter project defines the `server/` directory at the root, adjacent to the `app/` directory.
<img width="214" alt="image" src="https://github.com/user-attachments/assets/7e985284-1a50-4f07-8f4d-dc4627d13a96">

Is there a reason the server directory is outside of the app directory for this starter?

**Comment by bigredwill** [comment]
Ah! So this is a Nuxt v4 project, and nuxi perhaps is not compatible with this directory structure yet https://nuxt.com/docs/getting-started/upgrade#new-directory-structure

**Comment by bigredwill** [comment]
Closing this issue, filed with nuxi https://github.com/nuxt/cli/issues/551

**Comment by atinux** [comment]
Thanks for reporting it, we will improve the CLI!
