### ISSUE TITLE
defineNitroPlugin is not defined

### ISSUE THREAD

**Issue by evertontst** [nuxt-hub/starter#4]
When I tried to use this the migrations.ts I got this error

My code is:
import { consola } from "consola";
import { migrate } from "drizzle-orm/d1/migrator";

export default defineNitroPlugin(async () => {
  if (!import.meta.dev) return;

  onHubReady(async () => {
    await migrate(useDrizzle(), {
      migrationsFolder: "server/database/migrations",
    })
      .then(() => {
        consola.success("Database migrations done");
      })
      .catch((err) => {
        consola.error("Database migrations failed", err);
      });
  });
});

**Comment by atinux** [comment]
Could you update your dependencies and try again?
